# Generated by Django 2.2.5 on 2019-09-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PostSyufu',
            fields=[
                ('id_member', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('shufu_name', models.CharField(max_length=20)),
            ],
        ),
    ]
