# Generated by Django 2.2.5 on 2019-09-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.IntegerField(default=0)),
                ('user_adress', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Post_user',
        ),
    ]
